language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t seayeo1066/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true seayeo1066/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket-name: "elasticbeanstalk-us-east-2-992964360053"
  bucket-path: "docker-react"
  on:
    branch: master
  acceess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
